### ISSUE TITLE
Updates or deletes not appearing at pg_recvlogical

### ISSUE THREAD

**Issue by constructo** [ildus/decoder_json#1]
When reading the replication slot with the pg_recvlogical tool, only inserts appear (no matter if the table has primary keys or not).

pg_recvlogical -d postgres --slot json_slot --start -f -   

Other output plugins with the same configuration do show updates and deletes. For example https://bitbucket.org/btubbs/decoder_json/src which works as expected with inserts and updates (but fails with deletes') the json is made by concatenation , hence not too robust.

**Comment by ildus** [comment]
Hi, did you make tests?
