### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jdatcmd** [ildus/decoder_json#2]
We are curious what the license for decoder_json is?

**Comment by ildus** [comment]
It's free, there are no limitations.

**Comment by jdatcmd** [comment]
Just so I can be sure, you are saying it is public domain?

**Comment by ildus** [comment]
Yes

**Comment by jdatcmd** [comment]
You really should add a LICENSE file that states that. Thanks!

Also thanks for accepting my team mates patches!

**Comment by ildus** [comment]
Done!
